name: Terrapin Package Build

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
      name: Checkout source

    - name: Build package with Oryx
      run:  docker run --volume $(pwd):/repo --volume /home/runner/outputfolder:/output --env PRE_BUILD_COMMAND='dotnet run --project .github/workflows/PrebuildLogic.csproj && rm -rf /repo/.github/workflows/ && rm -rf /repo/.azure-pipelines/umask 0 && npm config set cache /tmp/.npm' mcr.microsoft.com/oryx/build:latest oryx build --package /repo/ --output /output -p registry=https://terraprod-wus2-functions.azurewebsites.net/api/npm/registry/default/

    - uses: jikuma/githubaction@v0.3.3-alpha
      name: Create release
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Terrapin release'
        release_note: 'Job: fbef191e-4d7a-419f-9f3b-3d03579f776d | Package: markdown-it@8.4.2 | Manager: Npm | Commit: ${{ github.sha }}'
        asset_filepath: '/home/runner/outputfolder/markdown-it-8.4.2.tgz'
        tag_name: v8.4.2+${{ github.sha }}
